//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSComponents.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BSComponents.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of neurons&apos; activation function:.
        /// </summary>
        internal static string activationFuncLabelText {
            get {
                return ResourceManager.GetString("activationFuncLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artificial neural network.
        /// </summary>
        internal static string ANNString {
            get {
                return ResourceManager.GetString("ANNString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The component &apos;Model builder&apos; is configured correctly..
        /// </summary>
        internal static string correctString {
            get {
                return ResourceManager.GetString("correctString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derivative.
        /// </summary>
        internal static string derivativeString {
            get {
                return ResourceManager.GetString("derivativeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourier transform.
        /// </summary>
        internal static string fourierTransform {
            get {
                return ResourceManager.GetString("fourierTransform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of neurons in hidden layers (with spaces between):.
        /// </summary>
        internal static string hiddenCountsLabelText {
            get {
                return ResourceManager.GetString("hiddenCountsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Fourier transform.
        /// </summary>
        internal static string inverseFourierTransform {
            get {
                return ResourceManager.GetString("inverseFourierTransform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of the training algorithm iterations:.
        /// </summary>
        internal static string maxIterationsCountLabelText {
            get {
                return ResourceManager.GetString("maxIterationsCountLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median filter.
        /// </summary>
        internal static string medianFilter {
            get {
                return ResourceManager.GetString("medianFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No model type was selected for the &apos;Model builder&apos; component..
        /// </summary>
        internal static string modelBuilderIsNullString {
            get {
                return ResourceManager.GetString("modelBuilderIsNullString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving average filter.
        /// </summary>
        internal static string movingAverageFilter {
            get {
                return ResourceManager.GetString("movingAverageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The change in network&apos;s output error, that will stop the training when it is reached:.
        /// </summary>
        internal static string stopErrorLabelText {
            get {
                return ResourceManager.GetString("stopErrorLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tukey53H filter.
        /// </summary>
        internal static string tukeyFilter {
            get {
                return ResourceManager.GetString("tukeyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weighted moving average filter.
        /// </summary>
        internal static string weightedMovingAverageFilter {
            get {
                return ResourceManager.GetString("weightedMovingAverageFilter", resourceCulture);
            }
        }
    }
}
